package coffee;

/**
 * TODO: Insert description here. (generated by houcy)
 */
public class ChocolateFlavorProcessor implements FlavorProcessor {
  public ChocolateFlavorProcessor () { }
  @Override
  public String toString() {
    return "ChocolateFlavorProcessor";
  }
}
