package coffee;

import dagger.Component;

/**
 * TODO: Insert description here. (generated by houcy)
 */
@Component (modules = {DripCoffeeModule.class, PumpModule.class})
public interface CoffeeMain {
  CoffeeMaker getCoffeeMaker();
}
