package coffee;

/**
 * TODO: Insert description here. (generated by houcy)
 */
public class Flavor {
  String name;
  public Flavor(String flavorName) {
    this.name = flavorName;
  }
  @Override
  public String toString() {
    return this.name;
  }
}
