package coffee;

/**
 * TODO: Insert description here. (generated by houcy)
 */
public class Flavor {
  String name;
  Flavor(String f) {
    this.name = f;
  }

  @Override public String toString() {
    return name;
  }
}
