package coffee;

/**
 * TODO: Insert description here. (generated by houcy)
 */
public class Flavor {
  String name;
  Flavor(String s) {
    this.name = s;
  }
  @Override public String toString() {
    return this.name;
  }
}
