package coffee;

import java.util.Map;

/**
 * TODO: Insert description here. (generated by houcy)
 */
public class MyLocation<K, V> implements Map.Entry<K, V> {
  private final K key;
  private V value;

  public MyLocation(K key, V value) {
    this.key = key;
    this.value = value;
  }

  @Override
  public K getKey() {
    // TODO(houcy): Auto-generated method stub
    return key;
  }

  @Override
  public V getValue() {
    // TODO(houcy): Auto-generated method stub
    return value;
  }

  @Override
  public V setValue(V value) {
    // TODO(houcy): Auto-generated method stub
    V old = this.value;
    this.value = value;
    return old;
  }
}
