package coffee;

/**
 * TODO: Insert description here. (generated by houcy)
 */
public class VanillaFlavorProcessor implements FlavorProcessor{
  public VanillaFlavorProcessor () { }
  
  @Override
  public String toString() {
    return "VanillaFlavorProcessor";
  }
}
